//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOTIV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.SubArea = new HashSet<SubArea>();
        }
    
        public int Area_id { get; set; }
        public string Area_Descripción { get; set; }
        public Nullable<int> Direccion_id { get; set; }
        public string Area_abreviatura { get; set; }
        public Nullable<bool> CentroServicioUsuario { get; set; }
    
        public virtual Direccion Direccion { get; set; }
        public virtual ICollection<SubArea> SubArea { get; set; }
    }
}
