//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOTIV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSU_TipoDeAtencion
    {
        public int TipoDeAtencion_Id { get; set; }
        public string TipoDeAtencion_Descripcion { get; set; }
        public Nullable<int> TipoDeAtencion_Padre_Id { get; set; }
        public Nullable<int> Area_Id { get; set; }
        public Nullable<int> PersonalResponsable_Id { get; set; }
    }
}
