//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOTIV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSU_MovimientoCSU
    {
        public int MovimientoCSU_Id { get; set; }
        public Nullable<int> CatalogoServicio_Id { get; set; }
        public Nullable<int> Persona_Id { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string AsuntoDeLaAtencion_Usuario { get; set; }
        public string AsuntoDeLaAtencion_Especilista { get; set; }
        public string DescripcionDeLaAtencion_Usuario { get; set; }
        public string DescripcionDeLaAtencion_Especialista { get; set; }
        public Nullable<int> Persona_Id_EspecialistaDesignado { get; set; }
        public Nullable<System.DateTime> FechaInicioDeAtencion { get; set; }
        public Nullable<System.DateTime> FechaCierreDeAtencion { get; set; }
        public Nullable<bool> Cerrado { get; set; }
        public string DecripcionEnCierre { get; set; }
        public Nullable<int> TiempoUtilizado { get; set; }
        public string Entregable { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string SolucionAplicada { get; set; }
        public Nullable<bool> Coyuntural { get; set; }
        public string CoyunturalObservacion { get; set; }
    }
}
