//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOTIV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public Direccion()
        {
            this.Area = new HashSet<Area>();
        }
    
        public int Direccion_id { get; set; }
        public string Direccion_descripción { get; set; }
        public string Direccion_abreviatura { get; set; }
    
        public virtual ICollection<Area> Area { get; set; }
    }
}
