//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOTIV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meta
    {
        public Meta()
        {
            this.MetaActividad = new HashSet<MetaActividad>();
            this.MetaEstado = new HashSet<MetaEstado>();
        }
    
        public int Meta_id { get; set; }
        public string Meta_descripcion { get; set; }
        public Nullable<int> SubArea_id { get; set; }
        public Nullable<bool> POI { get; set; }
        public Nullable<int> Version_id { get; set; }
        public Nullable<System.DateTime> Fecha_creacion { get; set; }
        public Nullable<int> ActividadPOI_Id { get; set; }
        public Nullable<bool> CumplimientoCompromisoPOI { get; set; }
    
        public virtual SubArea SubArea { get; set; }
        public virtual Version Version { get; set; }
        public virtual ICollection<MetaActividad> MetaActividad { get; set; }
        public virtual ICollection<MetaEstado> MetaEstado { get; set; }
    }
}
