//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOTIV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGP_Trama
    {
        public int TramaID { get; set; }
        public Nullable<int> Renaes { get; set; }
        public string TipoTrama { get; set; }
        public string NroExpediente { get; set; }
        public string DocumentoRecepcionado { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public Nullable<int> NumeroAtenciones { get; set; }
        public Nullable<System.DateTime> FechaProcesamiento { get; set; }
        public Nullable<int> NumeroAtencionesMigradas { get; set; }
        public Nullable<System.DateTime> ProduccionFissal { get; set; }
        public string Documentorespuesta { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> Atenciones2012 { get; set; }
        public Nullable<int> Atenciones2013 { get; set; }
        public Nullable<int> Atenciones2014 { get; set; }
        public Nullable<int> Atenciones2015 { get; set; }
        public Nullable<int> Atenciones2016 { get; set; }
        public Nullable<int> Atenciones2017 { get; set; }
        public Nullable<int> Atenciones2018 { get; set; }
        public Nullable<int> Atenciones2019 { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
