//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOTIV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGPRY_Actividad
    {
        public int Actividad_Id { get; set; }
        public string ActividadDescripcion { get; set; }
        public Nullable<int> HorasRequeridas { get; set; }
        public Nullable<int> HorasRequeridasHolgura { get; set; }
        public Nullable<int> RequisitoId { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaInicio_SinHolgura { get; set; }
        public Nullable<System.DateTime> FechaFin_SinHolgura { get; set; }
        public Nullable<System.DateTime> FechaInicio_ConHolgura { get; set; }
        public Nullable<System.DateTime> FechaFin_ConHolgura { get; set; }
        public Nullable<bool> Analisis { get; set; }
        public Nullable<System.DateTime> FechaCierreAnalisis { get; set; }
        public Nullable<bool> Desarrollo { get; set; }
        public Nullable<System.DateTime> FechaCierreDesarrollo { get; set; }
        public Nullable<bool> ControlCalidad { get; set; }
        public Nullable<System.DateTime> FechaCierreControlCalidad { get; set; }
    }
}
