//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOTIV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPE_ServicioTercero
    {
        public int ServicioTercero_Id { get; set; }
        public string Expediente_Id { get; set; }
        public Nullable<int> OrdenServicio { get; set; }
        public Nullable<System.DateTime> FechaOrdenServicio { get; set; }
        public Nullable<int> Persona_Id { get; set; }
        public string Servicio { get; set; }
        public string ProductosRequeridos { get; set; }
        public Nullable<int> PlazoEjecucion { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> Documento_Id_Conformidad { get; set; }
        public string ProductosEntregados { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> Anulado { get; set; }
    }
}
