//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOTIV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPE_AreaInstitucion
    {
        public SPE_AreaInstitucion()
        {
            this.SPE_Persona = new HashSet<SPE_Persona>();
        }
    
        public int AreaInstitucion_Id { get; set; }
        public string AreaInstitucionDescripcion { get; set; }
        public string AreaInstitucionAbreviatura { get; set; }
        public bool Fissal { get; set; }
    
        public virtual ICollection<SPE_Persona> SPE_Persona { get; set; }
    }
}
