//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOTIV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPS_DocumentosNormativos
    {
        public int Normatividad_Id { get; set; }
        public string Descripcion { get; set; }
        public string TipoDocumento { get; set; }
        public Nullable<System.DateTime> FechaPresentacion { get; set; }
        public string NumTramite { get; set; }
        public Nullable<int> PersonaId { get; set; }
        public Nullable<System.DateTime> FechaFormalizacion { get; set; }
        public string NumDocumento { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
