//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOTIV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPS_TareaAvance
    {
        public int TareaAvance_Id { get; set; }
        public string TareaAvanceDescripcion { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<bool> Dificultad { get; set; }
        public Nullable<bool> Anulado { get; set; }
        public Nullable<int> Tarea_Id { get; set; }
    }
}
