//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOTIV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPS_Reunion
    {
        public int ReunionId { get; set; }
        public Nullable<System.DateTime> FechaReunion { get; set; }
        public Nullable<int> ResponsableId { get; set; }
        public string Agenda { get; set; }
        public string TipoCoordinacion { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
