//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOTIV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_Expediente
    {
        public int Expediente_Id { get; set; }
        public string NroExpediente { get; set; }
        public string DocumentoAdjuntoExpediente { get; set; }
        public Nullable<System.DateTime> FechaRecepcionOTI { get; set; }
        public string Asunto { get; set; }
        public Nullable<int> UsuarioIdSolicitante { get; set; }
        public Nullable<int> UsuarioIdAtencion { get; set; }
        public Nullable<System.DateTime> FechaLimite { get; set; }
        public Nullable<bool> RequiereRespuesta { get; set; }
        public Nullable<int> UsuarioIdTecnicoDesignado { get; set; }
        public Nullable<bool> Atendido { get; set; }
        public Nullable<int> DocumentoAtención { get; set; }
        public Nullable<System.DateTime> FechaRecepcionSolicitante { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public Nullable<bool> OrigenOTI { get; set; }
        public Nullable<int> TipoDocumento { get; set; }
    }
}
