//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOTIV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Actividades_lista
    {
        public string Area_Descripción { get; set; }
        public string Area_abreviatura { get; set; }
        public string SubArea_Abreviatura { get; set; }
        public string SubArea_Descripción { get; set; }
        public int Meta_id { get; set; }
        public string Meta_descripcion { get; set; }
        public Nullable<bool> POI { get; set; }
        public int MetaActividad_id { get; set; }
        public string MetaActividad_descripcion { get; set; }
        public Nullable<System.DateTime> Fecha_ejecucion { get; set; }
        public Nullable<bool> Finalizado { get; set; }
        public Nullable<System.DateTime> Fecha_finalizacion { get; set; }
        public string DocumentoDeEntrega { get; set; }
        public long Id { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<int> Persona_Id { get; set; }
        public string Observacion { get; set; }
        public bool Desestimado { get; set; }
        public bool Reprogramado { get; set; }
        public bool ActividadDeInforme { get; set; }
        public Nullable<int> NumEventosUltimaSemana { get; set; }
    }
}
