//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOTIV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_resumen_avance_actividad
    {
        public Nullable<int> Año { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> ActividadesProgramadas { get; set; }
        public Nullable<int> ActividadesFinalizadas { get; set; }
        public long Id { get; set; }
        public Nullable<int> Metas { get; set; }
        public Nullable<int> ActividadesReprogramadas { get; set; }
    }
}
